---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: payments
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: {{ .Values.namespace }}
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        # vault.hashicorp.com/agent-inject: "true"
        # vault.hashicorp.com/agent-inject-token: "true"
        # vault.hashicorp.com/role: "vault"
        # vault.hashicorp.com/agent-init-first: "true"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9701"
        # consul.hashicorp.com/connect-service: payments
    spec:
      serviceAccountName: payments
      volumes:
        - name: properties
          configMap:
            name: app-properties
            items:
            - key: config
              path: application.properties
        - name: bootstrap
          configMap:
            name: bootstrap-payments
            items:
            - key: config
              path: bootstrap.yaml
      containers:
        - name: payments
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: properties
              mountPath: /application.properties
              subPath: application.properties
            - name: bootstrap
              mountPath: /bootstrap.yaml
              subPath: bootstrap.yaml