---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
  namespace: {{ .Values.namespace }}
  labels:
    app: payments
data:
  config: |
    app.storage=redis
    app.encryption.enabled={{ .Values.encryption.enabled }}
    app.encryption.path={{ .Values.encryption.engine }}
    app.encryption.key=payments
    spring.redis.host=redis
    spring.redis.port=6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap-payments
  namespace: {{ .Values.namespace }}
  labels:
    app: payments
data:
  config: |
    spring.cloud.vault:
      enabled: true
      host: vault.vault.svc.cluster.local
      port: 8200
      scheme: http
      fail-fast: true
      # generic:
      #   enabled: false
      # authentication: TOKEN
      # token: root
      authentication: KUBERNETES
      kubernetes:
        role: hashicups
        kubernetes-path: kubernetes
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      generic:
        enabled: false
      kv:
        enabled: false