apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: apps
  labels:
    app: payments
    myapp: payments
spec:
  selector:
    myapp: payments
  ports:
    - name: payments
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: apps
  labels:
    app: payments
    myapp: payments
automountServiceAccountToken: true