---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties-transform
  namespace: ${k8s_namespace}
  labels:
    app: payments
data:
  config: |
    app.storage=db
    app.encryption.enabled=true
    app.encryption.path=transform
    app.encryption.key=payments