FROM hashicorp/waypoint:latest as waypoint

FROM redis:${version}

COPY --from=waypoint /usr/bin/waypoint-entrypoint /usr/local/bin 
# COPY ./waypoint-entrypoint /usr/local/bin/

ENTRYPOINT [ "waypoint-entrypoint" ]

CMD [ "redis-server"]

