FROM hashicorp/waypoint:latest as waypoint

FROM dcanadillas/hashicups-payments:${version}

COPY --from=waypoint /usr/bin/waypoint-entrypoint /usr/local/bin 
# COPY ./waypoint-entrypoint /usr/local/bin/

ENTRYPOINT [ "waypoint-entrypoint" ] 
CMD [ "java", "-jar", "./spring-boot-payments-${jar_version}.jar" ]

