FROM hashicorp/waypoint:latest as waypoint

FROM hashicorpdemoapp/product-api-db:${version}

COPY --from=waypoint /usr/bin/waypoint-entrypoint /usr/local/bin 
# COPY ./waypoint-entrypoint /usr/local/bin/

ENTRYPOINT [ "waypoint-entrypoint" ]

CMD [ "docker-entrypoint.sh", "postgres" ]

