FROM openjdk:18.0.1-slim

COPY ./build/libs/spring-boot-payments-0.0.15.jar .

RUN apt update && \
  apt install -y curl unzip

RUN curl "https://releases.hashicorp.com/waypoint-entrypoint/0.8.1/waypoint-entrypoint_0.8.1_linux_amd64.zip" -o waypoint-entrypoint.zip

RUN unzip waypoint-entrypoint.zip && \ 
  mv waypoint-entrypoint /usr/local/bin/waypoint-entrypoint

ENTRYPOINT [ "/usr/local/bin/waypoint-entrypoint" ]

CMD ["java", "-jar", "./spring-boot-payments-0.0.15.jar"]
