apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      service: redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "9701"
      labels:
        app: redis
        service: redis
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        {{- with .Values.env }}
        env:
        {{- toYaml . | nindent 12 }}
        {{- end }}
        livenessProbe:
          failureThreshold: 30
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
        name: redis
        ports:
        - containerPort: 6379
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
      securityContext: {}
      serviceAccount: redis
      serviceAccountName: redis
