apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  # namespace: apps
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: nginx
          # namespace: apps # <== For Consul Enterprise Namespaces
          hosts: 
            - '*'
    # Vault (outside of the mesh) needs to connect to DB for Dynamic Secrets
    - port: 5432
      protocol: tcp
      services:
        - name: postgres
          # namespace: apps # <== For Consul Enterprise Namespaces